//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace WindowResize {
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {

        private static global::System.Resources.ResourceManager? resourceMan;

        private static global::System.Globalization.CultureInfo? resourceCulture;

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowResize.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo? Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string MenuResize {
            get {
                return ResourceManager.GetString("MenuResize", resourceCulture) ?? "Resize";
            }
        }

        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture) ?? "Settings...";
            }
        }

        internal static string MenuQuit {
            get {
                return ResourceManager.GetString("MenuQuit", resourceCulture) ?? "Quit Window Resize";
            }
        }

        internal static string MenuLoading {
            get {
                return ResourceManager.GetString("MenuLoading", resourceCulture) ?? "Loading...";
            }
        }

        internal static string MenuNoWindows {
            get {
                return ResourceManager.GetString("MenuNoWindows", resourceCulture) ?? "(No windows found)";
            }
        }

        internal static string MenuUntitled {
            get {
                return ResourceManager.GetString("MenuUntitled", resourceCulture) ?? "(Untitled)";
            }
        }

        internal static string AlertResizeFailedTitle {
            get {
                return ResourceManager.GetString("AlertResizeFailedTitle", resourceCulture) ?? "Resize Failed";
            }
        }

        internal static string AlertResizeFailedBody {
            get {
                return ResourceManager.GetString("AlertResizeFailedBody", resourceCulture) ?? "Could not resize the window.";
            }
        }

        internal static string AlertButtonOK {
            get {
                return ResourceManager.GetString("AlertButtonOK", resourceCulture) ?? "OK";
            }
        }

        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture) ?? "Window Resize Settings";
            }
        }

        internal static string SettingsPresetSizes {
            get {
                return ResourceManager.GetString("SettingsPresetSizes", resourceCulture) ?? "Preset Sizes";
            }
        }

        internal static string SettingsBuiltIn {
            get {
                return ResourceManager.GetString("SettingsBuiltIn", resourceCulture) ?? "Built-in";
            }
        }

        internal static string SettingsCustom {
            get {
                return ResourceManager.GetString("SettingsCustom", resourceCulture) ?? "Custom";
            }
        }

        internal static string SettingsNoCustomSizes {
            get {
                return ResourceManager.GetString("SettingsNoCustomSizes", resourceCulture) ?? "No custom sizes added";
            }
        }

        internal static string SettingsWidth {
            get {
                return ResourceManager.GetString("SettingsWidth", resourceCulture) ?? "Width";
            }
        }

        internal static string SettingsHeight {
            get {
                return ResourceManager.GetString("SettingsHeight", resourceCulture) ?? "Height";
            }
        }

        internal static string SettingsDimensionSeparator {
            get {
                return ResourceManager.GetString("SettingsDimensionSeparator", resourceCulture) ?? "x";
            }
        }

        internal static string SettingsAdd {
            get {
                return ResourceManager.GetString("SettingsAdd", resourceCulture) ?? "Add";
            }
        }

        internal static string SettingsRemove {
            get {
                return ResourceManager.GetString("SettingsRemove", resourceCulture) ?? "Remove";
            }
        }

        internal static string SettingsLaunchAtLogin {
            get {
                return ResourceManager.GetString("SettingsLaunchAtLogin", resourceCulture) ?? "Launch at Login";
            }
        }

        internal static string AlreadyRunningBody {
            get {
                return ResourceManager.GetString("AlreadyRunningBody", resourceCulture) ?? "Window Resize is already running.";
            }
        }
    }
}
